### ISSUE TITLE
Swagger로 API 명세서 작성

### ISSUE THREAD

**Issue by ezcolin2** [boostcampwm-2024/web15-OctoDocs#106]
## 어떤 기능인가요?
    
> Swagger를 통해 API 명세서를 만들어 쉽게 테스트할 수 있게 합니다.
    
## 작업 상세 내용
    
- [x] swagger 적용
- [x] 현재 API 명세서 작성
- [x] response dto 생성
    
## 참고할만한 자료(선택)
https://docs.nestjs.com/openapi/introduction (swagger 사용법)
https://medium.com/ayuth/proper-way-to-create-response-dto-in-nest-js-2d58b9e42bf9 (response dto 및 swagger)

**Comment by Tolerblanc** [comment]
- #102
