### ISSUE TITLE
노드를 움직일 때 엄청난 양의 쿼리가 발생하는 이슈

### ISSUE THREAD

**Issue by ezcolin2** [boostcampwm-2024/web15-OctoDocs#242]
## 어떤 버그인가요?

> 노드를 움직일 때 select, update 쿼리가 대량으로 발생합니다.

## 어떤 상황에서 발생한 버그인가요?

> 노드를 움직일 때

## 예상 결과

> 노드를 움직이다 떼었을 때만 쿼리가 발생해야 합니다.

**Comment by Tolerblanc** [comment]
#238 과 중복인 것 같습니다...! update 쿼리는 어느정도 줄어든 것 같은데, select 쿼리는 대량으로 날라가네요

**Comment by ezcolin2** [comment]
> #238 과 중복인 것 같습니다...! update 쿼리는 어느정도 줄어든 것 같은데, select 쿼리는 대량으로 날라가네요

앗 넵 닫아두겠습니다!
