### ISSUE TITLE
프로젝트 소개, 팀원 소개 복구 필요

### ISSUE THREAD

**Issue by djk01281** [boostcampwm-2024/web15-OctoDocs#61]
## 어떤 버그인가요?

> 프로젝트 소개, 팀원 소개 복구 필요

## 어떤 상황에서 발생한 버그인가요?

> Readme.md 사라짐.

## 예상 결과

> 프로젝트 소개, 팀원 소개.

**Comment by Tolerblanc** [comment]
#62 에서 복구 완료!
