### ISSUE TITLE
HoverTrigger 컴포넌트가 캔버스 interaction을 막는 문제

### ISSUE THREAD

**Issue by djk01281** [boostcampwm-2024/web15-OctoDocs#68]
## 어떤 버그인가요?

> `<HoverTrigger />` 컴포넌트가 캔버스 interaction을 막는 문제

## 어떤 상황에서 발생한 버그인가요?

https://github.com/user-attachments/assets/95f9829c-42d7-496b-b42f-59910dd71513

> `<HoverTrigger />` 영역에서, 캔버스 접근 시 관련 interaction이 작동되지 않음

## 예상 결과

> `<HoverTrigger />` 자체는 작동해서 `<SideBar />`가 열려 있지만 캔버스에는 접근이 가능하게 동작해야 할 것 같습니다.

**Comment by yewonJin** [comment]
이거 zIndex로 해결 못할 거 같다는 생각이 드네요.. 마우스 커서 x값 위치로 HoverTrigger 작동하도록 해야할 거 같은데 나중에 같이 얘기해보죠...

**Comment by djk01281** [comment]
사이드바 UI 변경으로 해결
