### ISSUE TITLE
에디터 Title 한글 중복 입력 문제

### ISSUE THREAD

**Issue by yewonJin** [boostcampwm-2024/web15-OctoDocs#97]
## 어떤 버그인가요?

에디터의 title를 수정할 때, 한글을 입력하면 이상하게 입력이 됩니다.

ex) "가나다"를 입력하면 "ㄱ가간나낟다"가 입력이 됩니다.

## 어떤 상황에서 발생한 버그인가요?

https://github.com/user-attachments/assets/d4ea5eb8-c8c2-4e20-8132-1958991e18ac

## 예상 결과

정상적인 한글이 입력이 되어야합니다.

ex) "가나다" -> "가나다"

**Comment by Tolerblanc** [comment]
이거 혹시 해결 가능한 문제인가요?? MacOS에서 앱 사용할 때 자주 이러던데 궁금하네욧

**Comment by djk01281** [comment]
> 이거 혹시 해결 가능한 문제인가요?? MacOS에서 앱 사용할 때 자주 이러던데 궁금하네욧

네 아마 어렵지 않을 거에요..! 내일 해보겠습니닷
